title: "Assignment 2"
author: "Anshjyot Singh (s215806) & Victor Jules René Andrevon-Canut (s232481) "
email: "215606@dtu.dk"
description: >-
  News reporting website based in SF
baseurl: "" 
url: "https://Anshjyot.github.io" 
github_username: "Anshjyot"

remote_theme: "daattali/beautiful-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap  
  - jekyll-paginate 
  - jekyll-archives 

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Visualizations"
    url: "/visualizations"
  - title: "Contact"
    url: "/contact"

collections:
  projects:
    output: true
    permalink: /projects/:title/

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
