title: "Final project"
author: "Anshjyot Singh (s215806) & Victor Jules René Andrevon-Canut (s232481) "
email: "s232481@dtu.dk"
description: >-
  Final project for 02806 Social Data Analysis and Visualization

baseurl: "" 
url: "https://victorandrevon.github.io/" 
github_username: "AictorAndrevon"

remote_theme: "daattali/beautiful-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap  
  - jekyll-paginate 
  - jekyll-archives 

navbar-links:
  Home: "index"
  Trend: "trend-analysis"
  Spatial: "spatial"
  Policy: "policy"

avatar: "/assets/images/avatar-icon.png"
round-avatar: true

#page-img: "/assets/images/background-nyc2.png"
#navbar-img: "/assets/images/background-nyc2.png"
#footer-img: "/assets/img/bgimage.png"

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

collections:
  projects:
    output: true
    permalink: /projects/:title/

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
