title: "Final project"
author: "Anshjyot Singh (s215806) & Victor Jules René Andrevon-Canut (s232481) "
email: "s232481@dtu.dk"
description: >-
  Final project for 02806 Social Data Analysis and Visualization

baseurl: "" 
url: "https://victorandrevon.github.io/" 
github_username: "AictorAndrevon"

remote_theme: "daattali/beautiful-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap  
  - jekyll-paginate 
  - jekyll-archives 

navbar-links:
  Home: "index"
  Trend: "trend-analysis"



collections:
  projects:
    output: true
    permalink: /projects/:title/

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
